server:
  tomcat:
    relaxed-query-chars: ["[", "]"] # 배열 쿼리 파라미터 대응
---
spring:
  config:
    activate:
      on-profile:
        - ci
        - local

server:
  port: 3001

domain:
  api: http://localhost:3001

---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 5000

domain:
  api: https://api.example.me
